# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "scad4r"
  s.version = "0.3.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Caleb Buxton"]
  s.date = "2013-03-08"
  s.description = "Provides Ruby affordances for scripting OpenSCAD"
  s.email = "me@cpb.ca"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".simplecov",
    "Gemfile",
    "Guardfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "features/result_parser.feature",
    "features/runner.feature",
    "features/step_definitions/result_parser_steps.rb",
    "features/step_definitions/runner_steps.rb",
    "features/support/env.rb",
    "lib/scad4r.rb",
    "lib/scad4r/notification.rb",
    "lib/scad4r/result_parser.rb",
    "lib/scad4r/runner.rb",
    "scad4r.gemspec",
    "spec/fixtures/scad/cube.csg",
    "spec/fixtures/scad/cube.scad",
    "spec/fixtures/scad/cube.stl",
    "spec/lib/scad4r/notification_spec.rb",
    "spec/lib/scad4r/result_parser_spec.rb",
    "spec/lib/scad4r/runner_spec.rb",
    "spec/lib/scad4r_spec.rb",
    "spec/shared_examples.rb",
    "spec/spec_helper.rb",
    "spec/support/openscad_execution_matcher.rb"
  ]
  s.homepage = "http://github.com/cpb/scad4r"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "Ruby wrapper for OpenSCAD"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<childprocess>, ["~> 0.3"])
      s.add_development_dependency(%q<aruba>, ["~> 0.5"])
      s.add_development_dependency(%q<growl>, ["~> 1.0"])
      s.add_development_dependency(%q<guard>, ["~> 1.6"])
      s.add_development_dependency(%q<guard-cucumber>, ["~> 1.3"])
      s.add_development_dependency(%q<guard-rspec>, ["~> 2.3"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_development_dependency(%q<pry>, ["~> 0.9"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<rspec>, ["~> 2.12"])
      s.add_development_dependency(%q<rb-fsevent>, ["~> 0.9"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.7"])
      s.add_development_dependency(%q<simplecov-csv>, ["~> 0.1"])
    else
      s.add_dependency(%q<childprocess>, ["~> 0.3"])
      s.add_dependency(%q<aruba>, ["~> 0.5"])
      s.add_dependency(%q<growl>, ["~> 1.0"])
      s.add_dependency(%q<guard>, ["~> 1.6"])
      s.add_dependency(%q<guard-cucumber>, ["~> 1.3"])
      s.add_dependency(%q<guard-rspec>, ["~> 2.3"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
      s.add_dependency(%q<pry>, ["~> 0.9"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<rspec>, ["~> 2.12"])
      s.add_dependency(%q<rb-fsevent>, ["~> 0.9"])
      s.add_dependency(%q<simplecov>, ["~> 0.7"])
      s.add_dependency(%q<simplecov-csv>, ["~> 0.1"])
    end
  else
    s.add_dependency(%q<childprocess>, ["~> 0.3"])
    s.add_dependency(%q<aruba>, ["~> 0.5"])
    s.add_dependency(%q<growl>, ["~> 1.0"])
    s.add_dependency(%q<guard>, ["~> 1.6"])
    s.add_dependency(%q<guard-cucumber>, ["~> 1.3"])
    s.add_dependency(%q<guard-rspec>, ["~> 2.3"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.3"])
    s.add_dependency(%q<pry>, ["~> 0.9"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<rspec>, ["~> 2.12"])
    s.add_dependency(%q<rb-fsevent>, ["~> 0.9"])
    s.add_dependency(%q<simplecov>, ["~> 0.7"])
    s.add_dependency(%q<simplecov-csv>, ["~> 0.1"])
  end
end

